-- phpMyAdmin SQL Dump
-- version 4.4.14
-- http://www.phpmyadmin.net
--
-- 主機: localhost
-- 產生時間： 2015 年 12 月 23 日 02:35
-- 伺服器版本: 5.6.26
-- PHP 版本： 5.5.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- 資料庫： `musictube`
--

-- --------------------------------------------------------

--
-- 資料表結構 `video`
--

CREATE TABLE IF NOT EXISTS `video` (
  `mid` int(11) NOT NULL,
  `title` text NOT NULL,
  `videoid` varchar(11) NOT NULL,
  `description` text NOT NULL,
  `thumbnail` tinytext CHARACTER SET latin1 NOT NULL,
  `tags` text NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;

--
-- 資料表的匯出資料 `video`
--

INSERT INTO `video` (`mid`, `title`, `videoid`, `description`, `thumbnail`, `tags`) VALUES
(1, '方文山電影同名主題曲【聽見下雨的聲音】完整MV 演唱:魏如昀 / 詞:方文山 / 曲:周杰倫', 'F2uX6ByoW7A', '方文山 編劇/導演 耗時近五年打造首部電影長片《聽見下雨的聲音》 用音樂與詩, 繪出青春的純 夢想的熱 愛情的澀｡ 2013.10.04 感動上映 【聽見下雨的聲音】電影原聲帶iTunes Store(台灣)預購: iTunes Store https://itunes.apple.com/tw/album/ting-jian-xia-yu-sheng-yin/id716614566?l=zh 下雨天, 有人說是天空在哭泣, 也有人說那是邂逅的天氣, 它是如此浪漫､富有情感與詩意｡ 《聽見下雨的聲音》, 是方文山親擬的片名, 電影故事以愛情題材為主軸, 從雨中展開愛戀, 以搖滾碰撞古典, 藉音樂與新詩刻劃青春的共同記憶｡ 出版過近10本書籍, 發表超過300首的歌詞創作, 對推廣中國古典文學富有使命感的方文山, 將自己鍾愛的韻腳詩､漢服､書法､水墨畫等中國傳統元素融入電影, 把詩詞的抽象意境具體轉化為影像, 讓電影的每個畫面, 都像明信片般唯美動人｡ 更特地邀請國寶級書法大師-董陽孜, 為電影片名題字, 打造出風格獨樹一幟的「方道」電影｡ 徐若瑄∣柯有倫∣韓雨潔∣釋小龍∣徐嬌∣Super Junior-M周覓 魏如昀∣八三夭-子瑜∣大飛∣鄒承恩∣康康∣林志炫∣品冠∣李東學∣侯佩岑 演員卡司組合獨特 為方文山鼓噪青春熾熱的聲音｡ 《聽見下雨的聲音》從網路「校園版微電影」揭開序幕, 描述故事主角們的大學時期, 熱愛音樂的阿倫(柯有倫 飾)與Sharon(徐若瑄 飾), 因共組樂團而發展出一段青澀純真的戀情｡ 而電影正片延續主角之後的人生故事, 下著雨的夏末, 阿倫在市集裡的漢服攤位遇見清新脫俗的雨婕(韓雨潔 飾), 兩人情感逐漸穩定之際, 阿倫的樂團卻因唱片公司決策變動使得團員間衝突不斷, 雨婕試圖分擔阿倫的煩惱卻又無力可施, 兩人難以跨越不同文化喜好的隔閡與無法溝通的障礙｡ ¬此時阿倫重遇已經成為搖滾天后的Sharon, 過往情愫在兩人之間再度¬悄然滋生...｡ 在青春歲月中, 我們也許都曾經遇過, 一個值得愛, 但卻無法分享夢想的人｡ 遇上與自己截然不同的戀人, 該如何跨越隔閡繼續愛, 或者, 選擇另一種愛他(她)的方式? 方文山 聽見魏如昀清亮震撼的聲音｡ 這部電影與音樂有著密不可分的關係, 方文山與老搭檔周杰倫更親自為電影打造同名主題曲---『聽見下雨的聲音』, 抒情搖滾曲風搭配新詩歌詞, 細膩描繪出女主角在愛情故事裡的心境｡ 主題曲由電影中飾演樂團鍵盤手Vicky的魏如昀演唱, 方文山說魏如昀從歌唱比賽出道, 歌唱實力堅強, 初次聽試唱Demo時就感到很震撼! 她的嗓音清亮高亢, 咬字又帶有獨特韻味, 把歌曲詮釋的力道十足層次豐富, 令方文山相當讚賞｡ --------------------------------------------------------------------------------------------------------------------- "聽見下雨的聲音" 試聽及下載連結: 1.KKBOX： http://kkbox.fm/7a0Eoj 2.myMusic： http://www.mymusic.net.tw/#!http://www.mymusic.net.tw/album/show/185193 3.Omusic http://music.fetnet.net/albumpage.php?album_id=1164754 4.中華電信 http://music.emome.net/download_check.jsp?musicnameid=233607&singerid=37212&cpid=02 5.遠傳電信： http://www.fetnet.net/RBT/public/PromoteDefaultDisplay 6.iTunes Store： https://itunes.apple.com/tw/album/ting-jian-xia-yu-sheng-yin/id704238678?l=zh', '', '周杰倫,完整版,高清,官方,杰威爾,周杰伦,完整,杰威尔,Jay,Chou,music,video,official,JVR,周傑倫,pop,Taiwan,台灣,袁詠琳,梁心頤,浪花兄弟,楊瑞代,好音樂,好藝人,台湾,袁咏琳,梁心颐,杨瑞代,好音乐,好艺人,魏如昀,方文山,聽見下雨的聲音,徐若瑄,柯有倫,電影,主題曲,繁體,周覓,釋小龍,chou mi,super junior,徐嬌,侯佩岑,康康,by2,李東學,'),
(2, '邱凱偉 Darren [ 愛越遠越重 Love Will Go The Distance ] MV -「春梅」插曲', 'H9WT74et_r8', '「春梅 HARU」電視原聲帶 ★6首台語原創新浪潮好歌+6首感動配樂 溫暖小生 邱凱偉 / 唱跳才女 袁詠琳 / 創作新人 葉懷佩 / 春梅女主角 林予晞 / 南拳媽媽 宋健彰 齊聚獻聲 方文山 / 黃俊郎 聯手打造最美台語新詩詞 真愛不管距離多遠只會越來越重, Darren好歌不管相隔多久只會越來越感動 Darren邱凱偉 深情詮釋 春梅插曲『愛越遠越重』 我們不管什麼年紀都要盡情愛到最後!! 邱凱偉首部時代劇｢春梅｣ 台､日雙語演出 獻唱濃郁鄉愁思念代表歌 創作唱跳全才女聲 袁詠琳, 3度為師兄量身創作､製作戲劇歌曲 台視時代大戲「春梅」帶觀眾重返1925年日治時期的台灣，透過女主角｢春梅｣一生不凡經歷與戀情，見證當時台灣人民的生活與情感故事。 Darren在｢春梅｣劇中飾演一名剛正不阿的日本軍官-宮本剛TSUYOSHI, 個性堅毅果決卻懷有一顆赤子之心。 在雍仁親王來台視察期間接下護衛任務, 一連串的農民抗爭事故讓他與12歲的春梅結下不解之緣。 懷抱著大日本理想的年輕軍官, 在體認現實殘酷與無奈後, 毅然辭去軍職重返台灣經商, 也因此與春梅再度重逢。 首次演出時代劇, Darren為角色下足苦功, 苦練日語, 更為把軍人形象詮釋到位而做了不少歷史研究。 Darren和師妹Cindy袁詠琳在戲劇音樂上有多次合作, 這回Darren挑戰時代劇, 也同樣力邀Cindy為自己打造代表歌曲, 對不諳台語的Cindy來說如何營造台灣味就頗具難度。 學習古典音樂出身的Cindy, 以優美的鋼琴曲調流暢營造抒情搖滾氣味, 淡然柔和的帶出宮本剛對這世情的惆悵心境。《愛越遠越重》主題與詞意也呼應劇中人物在苦悶時代不得已離鄉背井的甘苦與思念情懷。 ◆「春梅 HARU」電視原聲帶OST 下載Download/試聽Streaming ◆ ↬iTunes: https://goo.gl/wwr2pJ ↬KKBOX: http://kkbox.fm/Ra0gvE ↬myMusic: http://goo.gl/3aqv9B ↬Omusic: http://goo.gl/QACw4R ↬Hami+音樂: http://goo.gl/sE1RUz ↬FETnet-900: http://goo.gl/3jJmPf ↬Spotify: https://goo.gl/AH4W3z ◆「愛越遠越重」鈴聲下載 Ringtone ◆ ↬中華電信: 手機直撥700→按4→輸入代碼911744 ↬遠傳電信: 手機直撥900→按4→輸入代碼087738 ◆ Darren 邱凱偉 ◆ ↬Facebook: https://www.facebook.com/darren1218 ↬微博 Weibo: http://www.weibo.com/darren1218', '', '周杰倫,周董,周杰伦,Jay Chou (Musical Artist),Jay,袁詠琳,Cindy Yen,邱凱偉,DARREN,Lara,梁心頤,南拳媽媽,宋健彰,台視,春梅,HARU,八點檔,葉懷佩,Andrew Yeh,越唱越大聲,方文山,愛越遠越重,愛你一個人,電視原聲帶,林予晞,韓宜邦,楊子儀,王思平,李沛旭,朱德剛,席曼寧,林乃華,陳慕義,王凱,張珮瑩,李淑楨,吳朋奉,不能說的秘密,青花瓷,聽媽媽的話,葉惠美,taiwanese,台語,陳建瑋,宮本,黃俊郎,'),
(3, '周杰倫 Jay Chou【我要夏天 I Want Summer】Official MV (ft. Gary楊瑞代)', '3LFDEeLm0ss', '【我要夏天】周杰倫 X 楊瑞代 詞/曲: 周杰倫 陽光搖滾嘻哈，也是周杰倫最獨門的一種曲風，一開場就令人血脈賁張，炙熱的陽光、燙腳的沙灘、滿池的泳裝正妹。周杰倫和好哥兒們楊瑞代合唱，將熱血與青春表現得淋漓盡致，這首歌杰倫也玩了一下聲音表情，非常調皮生動；在編曲的部分後段加入了鄉村風格的編曲，令人驚艷。 --------------------------------------------------------------------------------- 我要夏天 I Want Summer 別怕曬的黑 看起來很健康 泳池旁的妹 笑起來很陽光 對你Say個Hey 出水芙蓉加甩頭 你是哪位 管他天多黑 反正還有月光 腳步繼續追 衝上沙灘的浪 越High越不累 音樂不停我們也停不下來 舉起手來 尖叫吶喊 螢光棒 仙女棒 管你還有什麼棒都一起搖擺 衝衝衝衝衝 衝向海邊 Go Go Go Go Go 準備瘋癲 我要夏天 在我耳邊碎碎唸 衝衝衝衝衝 衝向海邊 Go Go Go Go Go 到你身邊 別說再見 我已經開始想念 Hey Hey Hey Hey Hey Hey Hey Hey Hey Hey Hey Hey （我說）別怕曬的黑 看起來很健康 泳池旁的妹 笑起來很陽光 對你Say個Hey 出水芙蓉加甩頭 你（Hey） 是（Hey） 哪（Hey） 位（Hey） 管他天多黑 反正還有月光 腳步繼續追 衝上沙灘的浪 越High越不累 音樂不停我們也停不下來 舉起手來 尖叫吶喊 螢光棒 仙女棒 管你還有什麼棒都一起搖擺 衝衝衝衝衝 衝向海邊 Go Go Go Go Go 準備瘋癲 我要夏天 在我耳邊碎碎唸 衝衝衝衝衝 衝向海邊 Go Go Go Go Go 到你身邊 別說再見 我已經開始想念 衝衝衝衝衝 衝向海邊 Go Go Go Go Go 準備瘋癲 我要夏天 在我耳邊碎碎唸 衝衝衝衝衝 衝向海邊 Go Go Go Go Go 到你身邊 別說再見 我已經開始想念 Hey Hey Hey 已開始想念（Hey Hey Hey） Hey Hey Hey 已開始想念（Hey Hey Hey） ----------------------------------------------------------------------------------- ◆「哎呦，不錯哦」下載Download/試聽Streaming ◆ ↬ iTunes: http://goo.gl/blp3vC ↬ KKBOX: http://kkbox.fm/Ma0j2d ↬ myMusic: http://goo.gl/AJ1L2y ↬ Omusic: http://goo.gl/S5NvYk ↬ Hami+音樂: http://goo.gl/tromRr ↬ FETnet-900: http://goo.gl/9kOzLP ↬ Spotify: http://goo.gl/9IpABM ◆ 周杰倫 Jay Chou ◆ ↬ Facebook: http://www.facebook.com/jay ↬ 微博 Weibo (魔天倫世界巡迴演唱會): http://weibo.com/jay2013concert ↬ 微博 Weibo (Jay & Me粉絲社區): http://www.weibo.com/jayme0716 ↬ 杰威爾音樂官網 JVR Music Official Site: http://www.jvrmusic.com/', '', '周杰倫,Jay,Chou,周董,周杰伦,周傑倫,杰威尔,周周,袁詠琳,cindy,yen,官方,高清,我要夏天,楊瑞代,墾丁,summer,i want summer,jay chou,sprite,雪碧,小麥,杜哥,'),
(4, '周杰倫 Jay Chou【怎麼了 What''s Wrong】Official MV (ft. Cindy袁詠琳)', 'RcdscWaat_w', '【怎麼了】 詞：方文山 / 曲：周杰倫 女聲：Cindy 袁詠琳 (https://www.facebook.com/CindyJVRMusic) 取景於英國多佛著名的「白色懸崖」(White Cliffs) ------------------------------------------------------------------------------ 怎麼了 What''s Wrong 上車了 收拾心情揹上行李 我走了 一再重覆聽你喜歡 聽的歌 甜蜜回憶太多心亂了 真的 結束了 捨不得 你唱的生日快樂歌 還記得 你的溫柔方式終於 我懂了 話題聊到這裡你笑了 卻也 太遲了 我用咖啡拉花拉出白色的線 煮一杯眷戀 你側臉在咖啡表面 形成了思念 形成懷念 你長髮披肩 我漸漸的 勾劃出 你嘴角弧線 所有的從前 我慢慢的 喝掉有 你在的畫面 手中的寂寞續杯 苦了誰 清醒了當初離開你的感覺 在不是冬天季節 冷了離別 我還想聽你 叫我寶貝 怕你身邊 多了個誰 失眠的夜 獨自面對 花少了蝶 樹枯了葉 還想聽你 叫我寶貝 痛快心碎 或許乾脆 兩人世界 漫天的風雪 我愛過 的誰 怎麼了（你說呢） 為何溝通最後總是 我哭了（不說了） 承認犯錯又能如何 你選擇（我認了） 是不是我們都太自我 （自我） 藉口 要自由 沉默了（離開了） 明明彼此付出比誰 都要多（我才多） 卻相愛的比誰都要 不成熟（都怪我） 是不是等傷口都癒合（癒合） 才能 再擁有 我用咖啡拉花拉出白色的線 煮一杯眷戀 你側臉在咖啡表面 形成了思念 形成懷念 你長髮披肩 我漸漸的 勾畫出 你嘴角弧線（有你在的畫面） 所有的從前 我慢慢的 喝掉有 你在的畫面 手中的寂寞續杯 苦了誰 清醒了當初離開你的感覺 在不是冬天季節 冷了離別 我還想聽你 叫我寶貝 怕你身邊 多了個誰 失眠的夜 獨自面對 花少了蝶 樹枯了葉 還想聽你 叫我寶貝 痛快心碎 或許乾脆 兩人世界 漫天的風雪 我愛過 的誰 我還想聽你 叫我寶貝 怕你身邊 多了個誰 失眠的夜 獨自面對 花少了蝶 樹枯了葉 還想聽你 叫我寶貝 痛快心碎 或許乾脆 兩人世界 漫天的風雪 我愛過 的誰 ------------------------------------------------------------------------------- ◆「哎呦，不錯哦」下載Download/試聽Streaming ◆ ↬ iTunes: http://goo.gl/blp3vC ↬ KKBOX: http://kkbox.fm/Ma0j2d ↬ myMusic: http://goo.gl/AJ1L2y ↬ Omusic: http://goo.gl/S5NvYk ↬ Hami+音樂: http://goo.gl/tromRr ↬ FETnet-900: http://goo.gl/9kOzLP ↬ Spotify: http://goo.gl/9IpABM ◆【怎麼了】鈴聲下載 ◆ ↬ 中華電信: 手機直撥700→按4→輸入代碼828293 ↬ 遠傳電信: 手機直撥900→按4→輸入代碼289614 ◆ 周杰倫 Jay Chou ◆ ↬ Facebook: http://www.facebook.com/jay ↬ 微博 Weibo (魔天倫世界巡迴演唱會): http://weibo.com/jay2013concert ↬ 微博 Weibo (Jay & Me粉絲社區): http://www.weibo.com/jayme0716 ↬ 杰威爾音樂官網 JVR Music Official Site: http://www.jvrmusic.com/', '', '周杰倫,完整版,高清,官方,杰威爾,周杰伦,完整,杰威尔,Jay,Chou,official,JVR,周傑倫,pop,Taiwan,台灣,袁詠琳,台湾,袁咏琳,亞洲天王,不能說的秘密,青花瓷,方文山,周董,jay chou,cindy yen,怎麼了,英國,what''s wrong,白色懸崖,dover,zen-me-le,'),
(5, '周杰倫 Jay Chou【聽見下雨的聲音 Rhythm of the Rain】Official MV', 'zqKoXPHhmsM', '聽見下雨的聲音【Rhythm of the Rain】 詞：方文山 / 曲：周杰倫 這首歌是方文山執導的電影「聽見下雨的聲音」主題曲，之前是由魏如昀演唱的女生版本，這張專輯竟然重新收錄杰倫自己演唱的版本，真是給歌迷一個非常大的驚喜！非常值得珍藏。和女生版流露出淒美浪漫氛圍的不同，杰倫版的「聽見下雨的聲音」，主歌以低沉而寂寞的孤寂感吟唱著，帶著聽者回到愛情的回憶現場；到了副歌，卻彷彿在內心吶喊著對愛情的追憶與不捨；唱腔充滿戲劇張力，令人動容！ -------------------------------------------------------------------------- 聽見下雨的聲音 Rhythm of the Rain 竹籬上 停留著 蜻蜓 玻璃瓶裡插滿 小小 森林 青春 嫩綠的很 鮮明 百葉窗 折射的 光影 像有著心事的 一張 表情 而你 低頭拆信 想知道關於我的事情 青苔入鏡 簷下風鈴 搖晃曾經 回憶是 一行行無從 剪接的風景 愛始終年輕 而我聽見 下雨的聲音 想起你用唇語 說愛情 幸福也可以 很安靜 我付出一直 很小心 終於聽見 下雨的聲音 於是我的世界 被吵醒 就怕情緒紅 了眼睛 不捨的淚在 彼此的 臉上透明 百葉窗 折射的 光影 像有著心事的 一張 表情 而你 低頭拆信 想知道關於我的事情 愛在過境 緣份不停 誰在擔心 窗台上 滴落的雨滴 輕敲著傷心 淒美而動聽 而我聽見 下雨的聲音 想起你用唇語 說愛情 熱戀的時刻 最任性 不顧一切的 給約定 終於聽見 下雨的聲音 於是我的世界 被吵醒 發現你始終 很靠近 默默地陪在 我身邊 態度堅定 雨的聲音 -------------------------------------------------------------------------- ◆「哎呦，不錯哦」下載Download/試聽Streaming ◆ ↬ iTunes: http://goo.gl/blp3vC ↬ KKBOX: http://kkbox.fm/Ma0j2d ↬ myMusic: http://goo.gl/AJ1L2y ↬ Omusic: http://goo.gl/S5NvYk ↬ Hami+音樂: http://goo.gl/tromRr ↬ FETnet-900: http://goo.gl/9kOzLP ↬ Spotify: http://goo.gl/9IpABM ◆【聽見下雨的聲音】鈴聲下載◆ ↬ 中華電信: 手機直撥700→按4→輸入代碼828299 ↬ 遠傳電信: 手機直撥900→按4→輸入代碼289620 ◆ 周杰倫 Jay Chou ◆ ↬ Facebook: http://www.facebook.com/jay ↬ 微博 Weibo (魔天倫世界巡迴演唱會): http://weibo.com/jay2013concert ↬ 微博 Weibo (Jay & Me粉絲社區): http://www.weibo.com/jayme0716 ↬ 杰威爾音樂官網 JVR Music Official Site: http://www.jvrmusic.com/', '', '周董,周杰倫,完整版,高清,官方,杰威爾,周杰伦,完整,杰威尔,Jay,Chou,official,JVR,周傑倫,pop,Taiwan,台灣,台湾,亞洲天王,不能說的秘密,青花瓷,方文山,魔天倫,聽見下雨的聲音,官方完整,'),
(6, '周杰倫 Jay Chou【聽爸爸的話 Listen to Dad】Official MV', 'eS2T9IiOYbc', '【聽爸爸的話】 詞/曲：周杰倫 周杰倫再度令人驚艷之作，呼應自己的歌，男生小時候要聽媽媽的話，女生長大了要「聽爸爸的話」，在談戀愛時，明明是兩個人對於愛情的不對等而埋怨，女生有時候卻搬出爸爸來當分手的藉口，可是男生卻也以孝順為理由，聽媽媽的話，不能輕言放棄，誓言追回女生！ -------------------------------------------------------------- 聽爸爸的話 Listen to Dad 你聽爸爸的話 說我不是個好東西 送給你的花 不配放在你家花瓶裡 他要我越走越遠越好 不要在一起那最好 但我聽媽媽的話 要我不能輕易放棄 還喜歡的話讓我再追回你求求你 難道你要我不孝順嗎 這是藉口你應該懂吧 你說 誰說 我說 我不愛了 胡說 瞎說 我習慣了 那煙 和酒 也都戒了 證明有多在乎你了 光上 一句 我想你懂 我真 的不 太會說話 你看你 笑了吧 你說我 算了吧 一個人 的愛情 很簡單 兩個人 的相愛 為什麼反而變得很難 我受夠我的愛你比較多 也受夠你的愛沉默很久 承諾太多 多少會錯 你寧願難過也不要有結果 我受夠我的愛你比較多 倒不如回到從前的自由 說好放手 誰先開口 沒有對錯 反正花開了終究會落 你說 誰說 我說 我不愛了 胡說 瞎說 我習慣了 那煙 和酒 也都戒了 證明有多在乎你了 一個人 的愛情 很簡單 兩個人 的相愛 為什麼反而變得很難 你聽爸爸的話 說我不是個好東西 送給你的花 不配放在你家花瓶裡 他要我越走越遠越好 不要在一起那最好 但我聽媽媽的話 要我不能輕易放棄 還喜歡的話讓我再追回你求求你 難道你要我不孝順嗎 這是藉口你應該懂吧 我受夠我的愛你比較多 也受夠你的愛沉默很久 承諾太多 多少會錯 你寧願難過也不要有結果 我受夠我的愛你比較多 倒不如回到從前的自由 說好放手 誰先開口 沒有對錯 反正花開了終究會落 難道你要我不孝順嗎 這是藉口你應該懂吧 --------------------------------------------------------------- ◆「哎呦，不錯哦」下載Download/試聽Streaming ◆ ↬ iTunes: http://goo.gl/blp3vC ↬ KKBOX: http://kkbox.fm/Ma0j2d ↬ myMusic: http://goo.gl/AJ1L2y ↬ Omusic: http://goo.gl/S5NvYk ↬ Hami+音樂: http://goo.gl/tromRr ↬ FETnet-900: http://goo.gl/9kOzLP ↬ Spotify: http://goo.gl/9IpABM ◆【聽爸爸的話】鈴聲下載 ◆ ↬ 中華電信: 手機直撥700→按4→輸入代碼828297 ↬ 遠傳電信: 手機直撥900→按4→輸入代碼289618 ◆ 周杰倫 Jay Chou ◆ ↬ Facebook: http://www.facebook.com/jay ↬ 微博 Weibo (魔天倫世界巡迴演唱會): http://weibo.com/jay2013concert ↬ 微博 Weibo (Jay & Me粉絲社區): http://www.weibo.com/jayme0716 ↬ 杰威爾音樂官網 JVR Music Official Site: http://www.jvrmusic.com/', '', '周董,周杰倫,完整版,高清,官方,杰威爾,周杰伦,完整,杰威尔,Jay,Chou,music,video,official,JVR,周傑倫,pop,Taiwan,台灣,袁詠琳,梁心頤,浪花兄弟,楊瑞代,好音樂,好藝人,台湾,袁咏琳,梁心颐,杨瑞代,好音乐,好艺人,亞洲天王,不能說的秘密,天台,青花瓷,方文山,楊峻榮,葉惠美,魔天倫,演唱會,king,of,mandopop,聽爸爸的話,listen to dad,Ting-Ba-Ba-De-Hua,'),
(7, '周杰倫 Jay Chou【天涯過客 Passer-by】MV Lyrics Ver.', '8ahDPWGiMNE', '天涯過客 詞：方文山 曲：周杰倫 經典周杰倫式的中國風，搭上方文山絕美如詩的歌詞，以各種景寫情，將思念之情、愛情的遺憾、等待、各種細膩的情緒寫得含蓄卻又絲絲入扣。這首歌更首次來到千年古鎮--西塘取景，重現詞中的場景，這也是方文山繼執導「蘭亭序」MV之後，再度拍攝中國風的MV，不知又會拍出什麼令人驚艷的古裝大片？令人期待；這支MV也是周杰倫、方文山與Darren第三度合作，勢必再度掀起話題！ -------------------------------------------------------------------------- 天涯過客 風起雁南下 景蕭蕭 落黃沙 獨坐沏壺茶 沏成一夜 燈下 妳在 幾里外 的人家 想著他 一針一線 繡著花 晨霜攀黛瓦 抖落霜 冷了茶 撫琴欲對話 欲問琴聲 初落下 弦外 思念透窗花 而妳卻什麼也不回答 琴弦斷了 緣盡了 妳也走了 愛恨起落 故事經過 只留下我 幾番離愁 世事參透 都入酒 問妳是否 心不在這 少了什麼 琴弦斷了 緣已盡了 妳也走了 妳是過客 溫柔到這 沉默了 拱橋斜坡 水岸碼頭 誰記得 渡江扁舟 我傷依舊 臨行回頭 遠方誰揮手 古剎山嵐繞 霧散後 北風高 禪定我寂寥 我身後風 呼嘯 笛聲 半山腰 而妳在 哪座橋 遠遠對他 在微笑 亭外蘆葦花 白茫茫 細雨輕輕打 秋風颳 將筆擱下 畫不出 誰在瀟灑 情愫 竟短暫猶如 騷人墨客筆下的煙花 琴弦斷了 緣已盡了 妳也走了 愛恨起落 故事經過 只留下我 門前竹瘦 清風折柳 妳要走 風不停留 何苦繞來 搖晃燈火 琴弦斷了 緣已盡了 妳也走了 妳是過客 溫柔到這 沉默了 輕解繩索 紅塵放手 面對著 隨我擺渡 離岸東流 驀然回首 妳在渡船口 琴弦斷了 緣盡了 妳也走了 妳是過客 溫柔到這 沉默了 拱橋斜坡 水岸碼頭 誰記得 隨我擺渡 離岸東流 驀然回首 妳在渡船口 ------------------------------------------------------------------------- ◆「哎呦，不錯哦」下載Download/試聽Streaming ◆ ↬ iTunes: http://goo.gl/blp3vC ↬ KKBOX: http://kkbox.fm/Ma0j2d ↬ myMusic: http://goo.gl/AJ1L2y ↬ Omusic: http://goo.gl/S5NvYk ↬ Hami+音樂: http://goo.gl/tromRr ↬ FETnet-900: http://goo.gl/9kOzLP ↬ Spotify: http://goo.gl/9IpABM ◆【天涯過客】鈴聲下載 ◆ ↬ 中華電信: 手機直撥700→按4→輸入代碼828292 ↬ 遠傳電信: 手機直撥900→按4→輸入代碼289613 ◆ 周杰倫 Jay Chou ◆ ↬ Facebook: http://www.facebook.com/jay ↬ 微博 Weibo (魔天倫世界巡迴演唱會): http://weibo.com/jay2013concert ↬ 微博 Weibo (Jay & Me粉絲社區): http://www.weibo.com/jayme0716 ↬ 杰威爾音樂官網 JVR Music Official Site: http://www.jvrmusic.com/', '', '周董,周杰倫,完整版,高清,官方,杰威爾,周杰伦,完整,杰威尔,Jay,Chou,music,video,official,JVR,周傑倫,pop,Taiwan,台灣,袁詠琳,梁心頤,浪花兄弟,楊瑞代,好音樂,好藝人,台湾,袁咏琳,梁心颐,杨瑞代,好音乐,好艺人,亞洲天王,不能說的秘密,天台,青花瓷,方文山,楊峻榮,葉惠美,魔天倫,演唱會,king,of,mandopop,天涯過客,歌詞版,哎呦不錯哦,鞋子特大號,聽爸爸的話,算什麼男人,'),
(8, '周杰倫 Jay Chou【手寫的從前 Handwritten Past】Official MV', 'TMB6-YflpA4', '手寫的從前 詞：方文山 / 曲：周杰倫 這種抒情歌充滿了濃濃的純愛風，以「手寫」來表達校園的初戀，手寫的情書，傳遞的青春的溫度與純粹；令人嚮往；而這首歌最特別的就是第一遍以簡單的鋼琴伴奏，襯著周杰倫輕輕吟唱，彷彿在空盪的校園教室裡，安靜回憶著當時的初戀情景；間奏之後二段主歌截然不同，讓人意想不到，鼓聲一進之後曲風變饒舌，彷彿將時空拉回到初戀現場，那個曾經一起彈琴的公園、糖果店的青澀微甜。 --------------------------------------------------------------------- 手寫的從前 Handwritten Past 這風鈴 跟心動很接近 這封信 還在懷念旅行 路過的 愛情都太年輕 你是我想要 再回去的風景 這別離 被瓶裝成秘密 這雛菊 美的像詩句 而我在風中等你 的消息 等月光落雪地 等楓紅染秋季等相遇 我重溫午後 的陽光 將吉他斜揹 在肩上 跟多年前一樣 我們輕輕的唱 去任何地方 我看著你的臉 輕刷著和弦 情人節卡片 手寫的永遠 還記得廣場公園 一起表演 校園旁糖果店 記憶裡在微甜 我看著你的臉 輕刷著和弦 初戀是整遍 手寫的從前 還記得那年秋天 說了再見 當戀情已走遠 我將你深埋在 心裡面 微風需要竹林 溪流需要蜻蜓 鄉愁般的離開 需要片片浮萍 記得那年的雨季 回憶裡特安靜 哭過後的決定 是否還能進行 我傻傻等待 傻傻等春暖花開 等終等於等明等白 等愛情回來 青春屬於表白 陽光屬於窗台 而我想我屬於 一個擁有你的未來 紙上的彩虹 用素描畫的鐘 我還在修改 回憶之中你的笑容 該怎麼去形容 為思念醞釀的痛 夜空霓虹 都是我不要的繁榮 或許去趟沙灘 或許去看看夕陽 或許任何一個可以想心事的地方 情緒在咖啡館 被調成一篇文章 徹底愛上你如詩一般透明的淚光 我看著你的臉 輕刷著和弦 情人節卡片 手寫的永遠 還記得廣場公園 一起表演 校園旁糖果店 記憶裡在微甜 我看著你的臉 輕刷著和弦 初戀是整遍 手寫的從前 還記得那年秋天 說了再見 當戀情已走遠 我將你深埋在 心裡面 我重溫午後 的陽光 將吉他斜揹 在肩上 跟多年前一樣 我們輕輕的唱 去任何地方 我看著你的臉 輕刷著和弦 情人節卡片 手寫的永遠 還記得廣場公園 一起表演 校園旁糖果店 記憶裡在微甜 我看著你的臉 輕刷著和弦 初戀是整遍 手寫的從前 還記得那年秋天 說了再見 當戀情已走遠 我將你深埋在 心裡面 ---------------------------------------------------------------------- ◆「哎呦，不錯哦」下載Download/試聽Streaming ◆ ↬ iTunes: http://goo.gl/blp3vC ↬ KKBOX: http://kkbox.fm/Ma0j2d ↬ myMusic: http://goo.gl/AJ1L2y ↬ Omusic: http://goo.gl/S5NvYk ↬ Hami+音樂: http://goo.gl/tromRr ↬ FETnet-900: http://goo.gl/9kOzLP ↬ Spotify: http://goo.gl/9IpABM ◆【手寫的從前】鈴聲下載 ◆ ↬ 中華電信: 手機直撥700→按4→輸入代碼828296 ↬ 遠傳電信: 手機直撥900→按4→輸入代碼289617 ◆ 周杰倫 Jay Chou ◆ ↬ Facebook: http://www.facebook.com/jay ↬ 微博 Weibo (魔天倫世界巡迴演唱會): http://weibo.com/jay2013concert ↬ 微博 Weibo (Jay & Me粉絲社區): http://www.weibo.com/jayme0716 ↬ 杰威爾音樂官網 JVR Music Official Site: http://www.jvrmusic.com/', '', '周董,周杰倫,完整版,高清,官方,杰威爾,周杰伦,完整,杰威尔,Jay,Chou,music,video,official,JVR,周傑倫,pop,Taiwan,台灣,袁詠琳,梁心頤,浪花兄弟,楊瑞代,好音樂,好藝人,台湾,袁咏琳,梁心颐,杨瑞代,好音乐,好艺人,亞洲天王,不能說的秘密,天台,青花瓷,方文山,楊峻榮,葉惠美,魔天倫,演唱會,king,of,mandopop,手寫的從前,');

--
-- 已匯出資料表的索引
--

--
-- 資料表索引 `video`
--
ALTER TABLE `video`
  ADD PRIMARY KEY (`mid`);

--
-- 在匯出的資料表使用 AUTO_INCREMENT
--

--
-- 使用資料表 AUTO_INCREMENT `video`
--
ALTER TABLE `video`
  MODIFY `mid` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=9;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
